apiVersion: v1
kind: Namespace
metadata:
  name: iti-46
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-alpine-deployment
  namespace: iti-46
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-alpine
  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: FOO
              value: ITI
          ports:
            - containerPort: 80
